In [159]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.linear_model import LogisticRegression

In [160]:
df=pd.read_csv("placement_readiness_synthetic_10000.csv")
df['backlogs']=pd.to_numeric(df['backlogs'],errors='coerce')

In [161]:
df.head(5)

,name,email,gender,age,course,other_course,branch,year,cgpa,backlogs,...,comm_skill,apt_skill,team_skill,languages,certifications,participation,internship,training,placement,opinion
0,Kimberly Powell,zjuarez@petersen-hughes.com,Female,18,BCA,NaN,IT,Completed,5.55,NaN,...,5,3,4,C,NaN,Yes,Yes,Yes,Placed,Call find source entire matter civil threat ot...
1,Troy Erickson,bromero@watson.net,Male,25,B.Tech,NaN,Electrical,3rd Year,5.67,2.0,...,1,4,1,NaN,NaN,Yes,Yes,No,Placed,Five new decision threat industry investment i...
2,Kathy White,james99@hotmail.com,Female,20,B.Sc,NaN,CSE,4th Year,9.20,1.0,...,4,1,2,C,Data Analytics,No,Yes,Yes,Placed,Sport theory decide performance want fear wate...
3,Harold Obrien,gonzalezjames@romero-flores.info,Female,25,Other,Ceramics designer,CSE,2nd Year,6.71,NaN,...,5,3,4,NaN,Other;Cloud Computing,Yes,Yes,Yes,Placed,View standard role candidate surface gun prote...
4,Ariel Davis,wrightcraig@yahoo.com,Female,19,BCA,NaN,ECE,4th Year,6.40,NaN,...,1,5,1,JavaScript;Python;C,Data Analytics,Yes,No,No,Placed,Benefit least public their wife thousand power...

In [162]:
df.isnull().sum()

name                 0
email                0
gender               0
age                  0
course               0
other_course      8723
branch               0
year                 0
cgpa                 0
backlogs          5271
projects             0
tech_skill           0
comm_skill           0
apt_skill            0
team_skill           0
languages         2541
certifications    2586
participation        0
internship           0
training             0
placement            0
opinion              0
dtype: int64

In [163]:
x.describe()

,cgpa,projects,tech_skill,comm_skill,apt_skill,team_skill,internship
count,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000
mean,7.558717,5.094600,2.951500,2.97210,3.022500,3.027100,0.507700
std,1.442592,3.206163,1.383163,1.43392,1.421617,1.420129,0.499966
min,5.000000,0.000000,1.000000,1.00000,1.000000,1.000000,0.000000
25%,6.320000,2.000000,2.000000,2.00000,2.000000,2.000000,0.000000
50%,7.520000,5.000000,3.000000,3.00000,3.000000,3.000000,1.000000
75%,8.820000,8.000000,4.000000,4.00000,4.000000,4.000000,1.000000
max,10.000000,10.000000,5.000000,5.00000,5.000000,5.000000,1.000000

In [164]:
df.shape

(10000, 22)

In [165]:
x=df[["cgpa","backlogs","projects","tech_skill","comm_skill","apt_skill","team_skill","certifications","internship","training"]]
x['certifications']=x['certifications'].notna().astype(int)
x['internship']=(x['internship']=='Yes').astype(int)
x['training']=(x['training']=='Yes').astype(int)
x['backlogs']=((x['backlogs']<=1)&(x['backlogs'].notna())).astype(int)


x

/tmp/ipykernel_1812/1008515891.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['certifications']=x['certifications'].notna().astype(int)
/tmp/ipykernel_1812/1008515891.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['internship']=(x['internship']=='Yes').astype(int)
/tmp/ipykernel_1812/1008515891.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['training']=(x['training']=='Yes').astype(int)
/tmp/ipykernel_1812/1008515891.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x['backlogs']=((x['backlogs']<=1)&(x['backlogs'].notna())).astype(int)

,cgpa,backlogs,projects,tech_skill,comm_skill,apt_skill,team_skill,certifications,internship,training
0,5.55,0,1,3,5,3,4,0,1,1
1,5.67,0,9,3,1,4,1,0,1,0
2,9.20,1,10,5,4,1,2,1,1,1
3,6.71,0,7,2,5,3,4,1,1,1
4,6.40,0,3,3,1,5,1,1,0,0
...,...,...,...,...,...,...,...,...,...,...
9995,7.27,0,0,5,2,3,4,1,0,1
9996,7.34,0,9,3,5,1,3,0,0,1
9997,8.12,0,7,5,2,2,5,1,1,1
9998,6.71,0,7,2,4,3,5,1,1,0
9999,6.68,0,5,2,5,1,1,0,0,0

In [166]:
y=((x['cgpa']>5)&(x['backlogs']<=1)&(x["projects"]>=5)&(x['tech_skill']>=2)&(x['comm_skill']>=2)&(x['apt_skill']>=2)&(x['team_skill']>=2)&(x["certifications"].notna())&(x['internship']==1)&(x['training']==1))
y=y.astype(int)
y

0       0
1       0
2       0
3       1
4       0
       ..
9995    0
9996    0
9997    1
9998    0
9999    0
Length: 10000, dtype: int64

In [167]:
y.value_counts()
y.sum()

np.int64(598)

In [171]:
clf=LogisticRegression()
clf.fit(x,y)
example=clf.predict(([[6,1,6,4,4,3,5,1,0,1]]))
example

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])